### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by AdrienLemaire** [galki/material-ui-form#15]
https://github.com/unitedhubs/material-ui-form/blob/dev/package.json#L54
Are you sure react is a devDependency and not a dependency ?
You should probably also mention this on the README page.

----

https://github.com/unitedhubs/material-ui-form/blob/dev/src/components/Form.js#L12
Why not add all these methods as class methods ? You do not seem to use them elsewhere, and by interacting with the instance props, they become intertwined with the class.

----

https://github.com/unitedhubs/material-ui-form/blob/dev/src/components/Form.js#L190
You can simplify the enableSubmitButton and disableSubmitButton code as follow:
```
toggleSubmitButton() {
  this.setState({ disableSubmitButton: !this.state.disableSubmitButton })
}
```

----

In general:
- The code seriously lacks inline comments and docstrings. You will forget parts of the code and maintaining it will become difficult.
- Adding a simple example in the README comparing a form without your state/validation manager and a form with, to show how simpler it becomes, would make the package a lot more attractive to other developers.
- No unit tests is gonna be a no-go for many people.

Other than that, LGTM !

**Comment by galki** [comment]
@Fandekasp thanks for the thorough review!

> Are you sure react is a devDependency and not a dependency ?

im using react to build the src (devDependency), but users must also have react so i put it as `peerDependency` - but im not really sure how that works. is it wrong?

> Why not add all these methods as class methods ?

@skkap 's influence!

> You can simplify the enableSubmitButton ...

in this case id like to execute one-way (there may be many background events which can result in a wrong toggle value)

> The code seriously lacks inline comments and docstrings. You will forget parts of the code and maintaining it will become difficult.

https://github.com/unitedhubs/material-ui-form/issues/17

> Adding a simple example in the README ...

https://github.com/unitedhubs/material-ui-form/issues/18

> No unit tests is gonna be a no-go for many people.

i figured. this is where i really need help

**Comment by skkap** [comment]
> Why not add all these methods as class methods ?

To "simulate" private methods like in real programming languages.

There are various ways to do though. in ES6 can use this: https://medium.com/@davidrhyswhite/private-members-in-es6-db1ccd6128a5

**Comment by AdrienLemaire** [comment]
Closing since there's no specific action to be taken from this issue
