### ISSUE TITLE
add coverage

### ISSUE THREAD

**Issue by galki** [galki/material-ui-form#17]
- [ ] docstrings
- [x] Jest tests
- [x] linting

**Comment by AdrienLemaire** [comment]
Simplest way to go about increasing coverage with jest is making [snapshots](https://facebook.github.io/jest/docs/en/snapshot-testing.html) of [your components](https://github.com/unitedhubs/material-ui-form/tree/dev/src/components)

I'm used to writing jest tests with [Enzyme](https://github.com/airbnb/enzyme), quite simple to use:
* For unit tests, use `shallow`. It will only create a snapshot of the top component, hence you can test your top components attributes for example. Note that in addition, you can use `.find()` and other properties to search for children.
* For slower tests, use `mount`. This will save the full rendered version of all components including the top component. I usually try to avoid mounting, but for this plugin, this sounds like a good idea.

**Comment by galki** [comment]
@Fandekasp so as i understand it the `__tests__` folder should go in the `examples` folder ya?

**Comment by AdrienLemaire** [comment]
It should go in `src/components/`. You can create fake components in your tests if your components cannot be tested by themselves.

If you want to test your examples, you can also add `examples/__tests__`, but I wouldn't spend time on this.

**Comment by galki** [comment]
> You can create fake components in your tests if your components cannot be tested by themselves.

~the examples ARE fake components to make sure everything works - so are you still sure about that? is that some rule i dont know about?~ 

ok let me see what i can do

**Comment by galki** [comment]
also, how to you get enzyme to generate snapshots? (i can do it with jest but not with enzyme - are extra settings required?)

from what i understand `__shapshots__` must be committed for CI to check them correctly - but when using enzyme, that is not the case?

but enzyme-only seems to be working with CI so a little confused regarding this.

**Comment by galki** [comment]
alright i think i got it. `toMatchSnapshot` creates the snapshots. however now that im getting 50% coverage no idea how to get it back to 100!
