### ISSUE TITLE
Custom form and field attributes not rendering

### ISSUE THREAD

**Issue by jyodsh** [galki/material-ui-form#56]
I tried to add the default form attributes and some custom attributes in fields. But it's not rendering into dom.
Below is an example of my MaterialUIForm skeleton.
`<MaterialUIForm autoComplete="on" method="POST" action="example.com" name="my_form_name" id="form_id >  `

But in dom it looks like.
`<form autocomplete="on">`

As you can except "autocomplete" ,  no other attributes not working.

**Comment by galki** [comment]
done in https://github.com/unitedhubs/material-ui-form/pull/58
